# Generated by Django 3.2.8 on 2022-08-16 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flag', models.ImageField(blank=True, null=True, upload_to='country_flags')),
                ('iso', models.CharField(max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=True, verbose_name='Show on app')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'County',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Show on app')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='courses')),
                ('video', models.FileField(blank=True, null=True, upload_to='courses')),
                ('duration', models.IntegerField()),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('short_description', models.TextField(blank=True, max_length=500, null=True)),
                ('requirements', models.TextField(blank=True, max_length=500, null=True)),
                ('job_opportunities', models.TextField(blank=True, max_length=500, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training',
                'verbose_name_plural': 'Trainings',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='logos')),
                ('enabled', models.BooleanField(default=True, verbose_name='Show on app')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='technologies')),
                ('enabled', models.BooleanField(default=True, verbose_name='Show on app')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technology_language', to='school.language')),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.CreateModel(
            name='TrainerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Active profile')),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('niveau', models.CharField(choices=[('Secondaire', 'Secondaire'), ('BAC', 'BAC'), ('BAC+2', 'BAC+2'), ('Licence', 'Licence'), ('Maitrise', 'Maitrise'), ('Master', 'Master'), ('Doctorat', 'Doctorat')], max_length=50)),
                ('comments', models.TextField(blank=True, max_length=1000, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube', models.CharField(blank=True, max_length=100, null=True)),
                ('github', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('curriculum', models.ManyToManyField(related_name='courses_trainers', to='school.Course', verbose_name='Curriculum')),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_trainers', to='school.country', verbose_name='Country')),
                ('technologies', models.ManyToManyField(related_name='profile_technologies', to='school.Technology', verbose_name='Technologies')),
            ],
            options={
                'verbose_name': 'TrainerProfile',
                'verbose_name_plural': 'TrainerProfiles',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Active profile')),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('niveau', models.CharField(choices=[('Secondaire', 'Secondaire'), ('BAC', 'BAC'), ('BAC+2', 'BAC+2'), ('Licence', 'Licence'), ('Maitrise', 'Maitrise'), ('Master', 'Master'), ('Doctorat', 'Doctorat')], max_length=50)),
                ('comments', models.TextField(blank=True, max_length=1000, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube', models.CharField(blank=True, max_length=100, null=True)),
                ('github', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_students', to='school.country', verbose_name='Country')),
                ('technologies', models.ManyToManyField(related_name='technology_students', to='school.Technology', verbose_name='Technologies')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('addresse', models.CharField(max_length=200)),
                ('lat', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('long', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('enabled', models.BooleanField(default=True, verbose_name='Show on app')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_country', to='school.country', verbose_name='Site')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
            },
        ),
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Show on app')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='trainings')),
                ('video', models.FileField(blank=True, null=True, upload_to='trainings')),
                ('duration', models.IntegerField()),
                ('internship_duration', models.IntegerField()),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('short_description', models.TextField(blank=True, max_length=500, null=True)),
                ('requirements', models.TextField(blank=True, max_length=500, null=True)),
                ('job_opportunities', models.TextField(blank=True, max_length=500, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('curriculum', models.ManyToManyField(related_name='courses_parccours', to='school.Course', verbose_name='Curriculum')),
            ],
            options={
                'verbose_name': 'Training',
                'verbose_name_plural': 'Trainings',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technology_courses', to='school.technology', verbose_name='training'),
        ),
    ]
