# Generated by Django 3.2.8 on 2022-08-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag_emoji',
            field=models.CharField(default='l', max_length=100),
            preserve_default=False,
        ),
    ]
