# Generated by Django 3.2.8 on 2022-08-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_country_flag_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag_emoji',
            field=models.CharField(default='🇧🇯', max_length=100),
        ),
    ]
