# Generated by Django 4.1 on 2023-02-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_remove_customuser_fcm_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser", name="balance", field=models.FloatField(default=0),
        ),
    ]
