# Generated by Django 4.1 on 2023-04-07 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KitKot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(default="desciption", max_length=240)),
                ("tags", models.CharField(default="desciption", max_length=240)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="kitkot/uploads/images/"
                    ),
                ),
                ("video", models.FileField(upload_to="kitkot/uploads/video/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name": "KitKot", "verbose_name_plural": "KitKots",},
        ),
    ]
